create database SUPERMERCADO character set utf8mb4 collate utf8mb4_unicode_ci;

USE SUPERMERCADO;

CREATE TABLE PRODUTOS(
REFERENCIA VARCHAR(3) PRIMARY KEY,
DESCRICAO VARCHAR(50) UNIQUE,
ESTOQUE INT NOT NULL DEFAULT 0

);


INSERT INTO PRODUTOS VALUES ('001', 'FEIJÃO', 10);
INSERT INTO PRODUTOS VALUES ('002', 'ARROZ', 5);
INSERT INTO PRODUTOS VALUES ('003', 'FARINHA', 15);


SELECT * FROM PRODUTOS;


create table ITENSVENDA(
VENDA INT,
PRODUTO VARCHAR(3),
QUANTIDADE INT
);

INSERT INTO ITENSVENDA VALUES(1,'001',3);
insert INTO ITENSVENDA VALUES(1,'002',5);
INSERT INTO ITENSVENDA VALUES(1,'003',5);

DELIMITER ||
select * from ITENSVENDA||
delimiter ;

SELECT * FROM PRODUTOS;

DELIMITER ||
CREATE TRIGGER Tgr_ItensVenda_Delete After Delete on ITENSVENDA
for each row 
begin update PRODUTOS SET ESTOQUE = ESTOQUE + OLD.QUANTIDADE WHERE REFERENCIA = OLD.PRODUTO;
END||
DELIMIETER;

SHOW TRIGGERS;

DELIMITER $
CREATE TRIGGER Tgr_itensVenda_Insert AFTER INSERT ON ITENSVENDA FOR EACH ROW BEGIN UPDATE PRODUTOS SET ESTOQUE = ESTOQUE - NEW.QUANTIDADE WHERE REFERENCIA = NEW.PRODUTO; END$
SELECT * FROM PRODUTOS;
SHOW TRIGGERS;

DELETE FROM ITENSVENDA WHERE PRODUTO = '001' AND QUANTIDADE = 3;

SET SQL_SAFE_UPDATES = 0;
